### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [pvorb/sokrates#1]
Hi
The following lines have cryptographic API misuses. <br> File name => sokrates/src/main/java/de/vorb/sokrates/generator/Sha1ChecksumCalculator.java: Line number => 38: API name => MessageDigest:Unexpected call to method <java.security.MessageDigest: byte[] digest()> on object of type java.security.MessageDigest. Expect a call to one of the following methods <java.security.MessageDigest: void update(byte[])>,<java.security.MessageDigest: void update(byte[],int,int)>,<java.security.MessageDigest: byte[] digest(byte[])>,<java.security.MessageDigest: void update(java.nio.ByteBuffer)>,<java.security.MessageDigest: void update(byte)><BR> File name => sokrates/src/main/java/de/vorb/sokrates/generator/Sha1ChecksumCalculator.java: Line number => 30: API name => MessageDigest:<BR>

**Comment by pvorb** [comment]
Closing this issue because it is auto-generated and I can't make much sense of it.
